dist: bionic

language: python

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y swig

install:
 - pip install --upgrade setuptools pip
 - pip install tox

script:
  - tox

after_success:
  - source .tox/${TOXENV}/bin/activate && pip install codecov && codecov --env TRAVIS_OS_NAME,TOXENV

env:
  global:
    - PYTHONWARNINGS=always::DeprecationWarning
  matrix:
    - TOXENV=lint
    - TOXENV=py27
matrix:
  include:
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py36
  allow_failures:
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
