os: linux
dist: bionic

language: python

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y swig

install:
 - pip install --upgrade setuptools pip
 - pip install tox

script:
  - tox

after_success:
  - source .tox/${TOXENV}/bin/activate && pip install codecov && codecov --env TRAVIS_OS_NAME,TOXENV

env:
  global:
    - PYTHONWARNINGS=always::DeprecationWarning
  jobs:
    - TOXENV=lint
jobs:
  include:
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37
    - python: "3.8"
      env: TOXENV=py38
    - python: "3.9"
      env: TOXENV=py39
